/**
 * @fileoverview Environment and configuration helpers with .env example generation.
 *
 * This module provides utilities to access environment variables with type parsing, validation, and automatic .env.example generation. It includes helper functions for common types like numbers, booleans, URLs, and more. The `get()` function is the core accessor that supports various options for requiredness, defaults, allowed values, and custom parsers.
 *
 * @example
 * import { get, num, env, config } from '$lib/server/utils/env';
 * const apiKey = get('API_KEY', { required: true });
 * const port = num('PORT', false) ?? config.network.port;
 * console.log(env);
 */
import { config as dotenv } from 'dotenv';
import fs from 'fs';
import path from 'path';
import { z } from 'zod';
dotenv();

let timeout: ReturnType<typeof setTimeout>;
const keys = new Map<
	string,
	{
		required: boolean;
		default?: unknown;
		type?: string;
		comment?: string;
	}
>();

const cache = new Map<string, unknown>();

/**
 * Error thrown for invalid or missing environment configuration.
 */
export class EnvironmentError extends Error {
	constructor(message: string) {
		super(message);
		this.name = 'EnvironmentError';
	}
}

/**
 * Options for `get()` environment accessor.
 *
 * @property {boolean} [required] - Whether the env var must be present.
 * @property {T} [default] - Default value when missing.
 * @property {T} [devDefault] - Default value in development when missing.
 * @property {string[]} [values] - Allowed raw string values.
 * @property {(val: string) => T} [parser] - Parser for raw value.
 * @property {string} [type] - Human-readable type for .env.example.
 */
type EnvConfig<T> = {
	required?: boolean;
	default?: T;
	devDefault?: T;
	values?: string[];
	parser?: (val: string) => T;
	type?: string;
	comment?: string;
};

const exampleFilepath = path.join(process.cwd(), '.env.example');
const envFilepath = path.join(process.cwd(), '.env');
let current = '';
try {
	current = fs.readFileSync(exampleFilepath, 'utf-8');
} catch {
	console.log('.env.example does not exist, will create it automatically');
}

/**
 * Current environment name.
 */
export const env = process.env.ENVIRONMENT || 'dev';

/**
 * Schedules a .env.example update based on requested keys.
 */
function generateExample() {
	if (timeout) clearTimeout(timeout);
	timeout = setTimeout(async () => {
		const currentLines = current.split('\n').map((l) => l.trim());

		if (currentLines.length === 1 && currentLines[0] === '') {
			currentLines.push('# This file was auto-generated by src/lib/server/utils/env-utils.ts');
			currentLines.push('# Feel free to comment and to replace default example values');
			currentLines.push('');
		}

		for (const [key, { required, default: def, type, comment: keyComment }] of keys) {
			if (currentLines.find((l) => l.startsWith(key + '='))) continue;
			console.log('Adding to env example:', key, type);

			let comment = `${required ? '# Required' : ''}`;
			if (type) {
				if (comment.length) comment += ` (${type})`;
				else comment += `# (${type})`;
			}
			if (keyComment) {
				if (comment.length) comment += ` - ${keyComment}`;
				else comment += `# ${keyComment}`;
			}

			currentLines.push(`${key}=${def ?? `some_${key.toLowerCase()}`} ${comment}`);
		}
		fs.writeFileSync(exampleFilepath, currentLines.join('\n'));

		keys.clear();
	}, 1000);
}

// Overloads for get()
/**
 * Gets an environment variable with optional parsing/validation.
 *
 * @param {string} key - Environment key (case-insensitive).
 * @param {EnvConfig<T>} [config] - Accessor config.
 */
export function get<T = string>(key: string, config: EnvConfig<T> & { required: true }): T;
export function get<T = string>(key: string, config?: EnvConfig<T>): T | undefined;
export function get<T = string>(key: string, config?: EnvConfig<T>): T | undefined {
	if (cache.has(key)) return cache.get(key) as T;
	key = key.toUpperCase();
	const skipValidation = process.env.SKIP_ENV_VALIDATION === '1';
	const parse = (val: string) => (config?.parser ? config.parser(val) : (val as unknown as T));
	const gen = (data: T) => {
		cache.set(key, data);
		if (process.env.ENVIRONMENT === 'prod') return; // Don't change git-tracked files in production
		if (!keys.has(key)) {
			keys.set(key, {
				required: config?.required ?? false,
				default: config?.default,
				type: config?.type,
				comment: config?.comment
			});
			generateExample();
		}
	};
	const raw = process.env[key];

	if (config?.required && (config.default !== undefined || config.devDefault !== undefined)) {
		throw new EnvironmentError(
			`Env var "${key}" cannot be required and have a default or devDefault`
		);
	}

	if (config?.required && !raw && !skipValidation) {
		throw new EnvironmentError(`Missing required env var "${key}"`);
	}

	if (config?.required && !raw && skipValidation) {
		const fallbackRaw = (() => {
			if (config.values?.length) return config.values[0];
			if (config.type === 'URL') return 'http://localhost';
			if (config.type === 'email') return 'build@example.com';
			if (config.type === 'number') return '0';
			if (config.type === 'number[]') return '0';
			if (config.type === 'y/n, true/false, 1/0') return 'false';
			if (config.type === 'string[]') return 'build';
			return 'build';
		})();

		const fallback = parse(fallbackRaw);
		gen(fallback);
		return fallback;
	}

	if (raw) {
		if (config?.values && !config.values.includes(raw)) {
			throw new EnvironmentError(
				`Invalid raw value for env var "${key}". Must be one of: ${config.values.join(', ')}`
			);
		}
		const actual = parse(raw);
		if (
			(config?.default !== undefined && typeof config.default !== typeof actual) ||
			(config?.devDefault !== undefined && typeof config.devDefault !== typeof actual)
		) {
			throw new EnvironmentError(
				`Env var "${key}" has a different type than the provided default/devDefault`
			);
		}
		gen(actual);
		return actual;
	}

	if (process.env.NODE_ENV === 'development' && config?.devDefault !== undefined) {
		gen(config.devDefault);
		return config.devDefault;
	}

	gen(config?.default as T);
	return config?.default;
}

// ===== Helper functions with correct typing =====

// Number helpers
/**
 * Reads a numeric env var.
 *
 * @param {string} key - Environment key.
 * @param {boolean} required - Whether the key is required.
 * @param {string} [comment] - Optional comment for the env var.
 */
export function num(key: string, required: true, comment?: string): number;
export function num(key: string, required: false, comment?: string): number | undefined;
export function num(key: string, required: boolean, comment?: string): number | undefined {
	const res = get<number>(key, {
		required: required ?? false,
		parser: (val) => parseInt(val),
		type: 'number',
		comment
	});
	if (res !== undefined && isNaN(res)) {
		throw new EnvironmentError(`Env var "${key}" is not a valid number`);
	}

	return res;
}

// Boolean helpers
/**
 * Reads a boolean env var.
 *
 * @param {string} key - Environment key.
 * @param {boolean} required - Whether the key is required.
 * @param {string} [comment] - Optional comment for the env var.
 */
export function bool(key: string, required: true, comment?: string): boolean;
export function bool(key: string, required: false, comment?: string): boolean | undefined;
export function bool(key: string, required: boolean, comment?: string): boolean | undefined {
	return get<boolean>(key, {
		required: required ?? false,
		parser: (val) => ['true', 'y', '1'].includes(val.toLowerCase()),
		type: 'y/n, true/false, 1/0',
		values: ['y', 'n', 'Y', 'N', 'true', 'false', 'TRUE', 'FALSE', 'True', 'False', '1', '0'],
		comment
	});
}

// String helpers
/**
 * Reads a string env var.
 *
 * @param {string} key - Environment key.
 * @param {boolean} required - Whether the key is required.
 * @param {string} [comment] - Optional comment for the env var.
 */
export function str(key: string, required: true, comment?: string): string;
export function str(key: string, required: false, comment?: string): string | undefined;
export function str(key: string, required: boolean, comment?: string): string | undefined {
	return get<string>(key, { required: required ?? false, comment });
}

export function arr(key: string, type: 'string', required: true, comment?: string): string[];
export function arr(key: string, type: 'number', required: true, comment?: string): number[];
export function arr(
	key: string,
	type: 'string',
	required: false,
	comment?: string
): string[] | undefined;
export function arr(
	key: string,
	type: 'number',
	required: false,
	comment?: string
): number[] | undefined;
export function arr(
	key: string,
	type: 'string' | 'number',
	required: boolean,
	comment?: string
): (string[] | number[]) | undefined {
	const parser = (val: string) => {
		const parts = val.split(',').map((p) => p.trim());
		if (type === 'number') {
			const nums = parts.map((p) => parseFloat(p));
			if (nums.some((n) => isNaN(n))) {
				throw new EnvironmentError(`Env var "${key}" contains invalid number in array`);
			}
			return nums;
		}
		return parts;
	};
	return get(key, { required, parser, type: `${type}[]`, comment });
}

export function url(key: string, required: true, comment?: string): string;
export function url(key: string, required: false, comment?: string): string | undefined;
export function url(key: string, required: boolean, comment?: string): string | undefined {
	const parser = (val: string) => {
		try {
			return new URL(val).toString();
		} catch {
			throw new EnvironmentError(`Env var "${key}" is not a valid URL`);
		}
	};
	return get(key, { required, parser, type: 'URL', comment });
}

export function email(key: string, required: true, comment?: string): string;
export function email(key: string, required: false, comment?: string): string | undefined;
export function email(key: string, required: boolean, comment?: string): string | undefined {
	const parser = (val: string) => {
		const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
		if (!emailRegex.test(val)) {
			throw new EnvironmentError(`Env var "${key}" is not a valid email address`);
		}
		return val;
	};
	return get(key, { required, parser, type: 'email', comment });
}

export function union<T extends string>(
	key: string,
	values: T[],
	required: true,
	comment?: string
): T;
export function union<T extends string>(
	key: string,
	values: T[],
	required: false,
	comment?: string
): T | undefined;
export function union<T extends string>(
	key: string,
	values: T[],
	required: boolean,
	comment?: string
): T | undefined {
	return get(key, { required, values, type: values.join('|'), comment });
}
export function enum_str<T extends string>(
	key: string,
	values: T[],
	required: true,
	comment?: string
): T;
export function enum_str<T extends string>(
	key: string,
	values: T[],
	required: false,
	comment?: string
): T | undefined;
export function enum_str<T extends string>(
	key: string,
	values: T[],
	required: boolean,
	comment?: string
): T | undefined {
	const parser = (val: string) => {
		if (!values.includes(val as T)) {
			throw new EnvironmentError(`Env var "${key}" is not a valid enum value`);
		}
		return val as T;
	};
	return get(key, { required, parser, type: 'enum', comment });
}

/**
 * Builds a public domain string from config.
 *
 * @param {{ port: boolean; protocol: boolean }} domainConfig - Formatting options.
 */
export function domain(domainConfig: { port: boolean; protocol: boolean }) {
	const host = str('SITE_URL', true);
	const port = num('PORT', true);
	const protocol = str('PROTOCOL', true) + '://';

	return `${domainConfig.protocol ? protocol : ''}${host}${domainConfig.port ? `:${port}` : ''}`;
}

/**
 * Fetches the public IPv4 address for the running instance.
 */
export const getPublicIp = async () => {
	const res = await fetch('https://api.ipify.org?format=json');
	if (!res.ok) {
		console.error('Error fetching public IP:', res.status, res.statusText);
		return null;
	}
	const parsed = z
		.object({
			ip: z.string().ip({
				version: 'v4'
			})
		})
		.safeParse(await res.json());

	if (!parsed.success) {
		console.error('Error parsing public IP response:', parsed.error);
		return null;
	}
	return parsed.data.ip;
};

export const set = (vars: Record<string, string>) => {
	if (env === 'prod') {
		throw new EnvironmentError('Cannot set environment variables in production');
	}
	console.log('Setting environment variables:', JSON.stringify(vars, null, 2));
	let current = '';
	try {
		current = fs.readFileSync(exampleFilepath, 'utf-8');
	} catch {
		console.log('.env.example does not exist, will create it automatically');
	}
	const currentLines = current.split('\n').map((l) => l.trim());

	if (currentLines.length === 1 && currentLines[0] === '') {
		currentLines.push('# This file was auto-generated by src/lib/server/utils/env.ts');
		currentLines.push('# Feel free to comment and to replace default example values');
		currentLines.push('');
	}

	for (const [key, value] of Object.entries(vars)) {
		process.env[key] = value;
		// overwrite existing key in .env.example or add if missing
		const existingIndex = currentLines.findIndex((l) => l.startsWith(key + '='));
		if (existingIndex !== -1) {
			currentLines[existingIndex] = `${key}=${value}`;
		} else {
			currentLines.push(`${key}=${value}`);
		}
	}
	fs.writeFileSync(envFilepath, currentLines.join('\n'));
};
