name: e2e

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  e2e-tests:
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    # this has a chance of infinite loop if we write a test wrong, timeout should catch it eventually.
    timeout-minutes: 5
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - uses: pnpm/action-setup@v6
        with:
          version: 10.30.0

      - uses: actions/setup-node@v7
        with:
          node-version: 24.13.1
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Load .env variables
        run: |
          cp .env.example .env
          echo "Loaded .env variables"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm add -D typescript@5.9.3
          pnpm install --frozen-lockfile
          pnpm exec playwright install

      - name: Set up Supabase Config
        run: |
          echo "Setting up Supabase config..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SCHEMA_NAME="e2e_test_${COMMIT_HASH}"
          sed -i "s/^project_id = .*/project_id = \"${SCHEMA_NAME}\"/" supabase/config.toml
          pnpm script supabase/sb-random-ports
          pnpm sb:start --debug
          echo "Waiting for supabase to be ready..."
          until pnpm run sb:status | grep -q "Development Tools"; do
            echo "Supabase not ready yet, waiting..."
            sleep 5
          done
          echo "Configuring local supabase"
          pnpm run sb:local-config
          pnpm run sb:push

      # - name: Init supabase types
      #   run: |
      #     pnpm run sb:pull-types

      - name: Run
        run: |
          echo "Running e2e tests..."
          pnpm run test:e2e

      - name: Shutdown supabase
        if: always()
        run: |
          pnpm sb:stop --no-backup || true
          docker rm -f $(docker ps -aq --filter "name=supabase-${SCHEMA_NAME}") || true

      - name: Clean up Supabase config
        if: always()
        run: rm -f .env
