name: Unit Tests

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  unit-tests:
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node v24.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 24.13.1
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.0

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm add -D typescript
          pnpm install --frozen-lockfile

      - name: Load .env variables
        run: |
          cp .env.example .env
          echo "Loaded .env variables"

      - name: Set up Supabase Config
        run: |
          echo "Setting up Supabase config..."
          COMMIT_HASH=$(git rev-parse --short HEAD)
          SCHEMA_NAME="unit_test_${COMMIT_HASH}"
          echo "Setting schema to ${SCHEMA_NAME}..."
          pnpm run sb:set-schema ${SCHEMA_NAME}
          sed -i "s/^project_id = .*/project_id = \"${SCHEMA_NAME}\"/" supabase/config.toml
          pnpm script supabase/sb-random-ports
          pnpm sb:start --debug
          echo "Waiting for supabase to be ready..."
          until pnpm run sb:status | grep -q "Development Tools"; do
            echo "Supabase not ready yet, waiting..."
            sleep 5
          done
          echo "Configuring local supabase"
          pnpm run sb:local-config
          pnpm run sb:push

      # - name: Init supabase types
      #   run: pnpm run sb:pull-types

      - name: Run Vitest tests
        run: npm run test:unit

      - name: Shutdown supabase
        if: always()
        run: |
          pnpm sb:stop --no-backup || true
          docker rm -f $(docker ps -aq --filter "name=supabase-${SCHEMA_NAME}") || true

      - name: Clean up Supabase config
        if: always()
        run: rm -f .env
